### ISSUE TITLE
Almost Unsoundness bug :)

### ISSUE THREAD

**Issue by elichai** [Michael-F-Bryan/const-arrayvec#2]
I was sure this was an unsoundness bug but right before I posted I realized it's actually not, but still needs changing IMHO.

`try_insert()` checks if the index is bigger then the len `index > self.len()`, otherwise panics.
https://github.com/Michael-F-Bryan/const-arrayvec/blob/master/src/lib.rs#L241:L270

Right now it also has a check if the array full, which in my opinion should be removed (you should still be able to insert something on index 2 in a [T; 8] array even if it's full).
*BUT* removing that check will right now introduce an unsoundness bug, because then you could pass `index = len` and it will write out of bound.

the check should be `index >= self.len()` because doing `[1u8; 8][8]` is obviously out of bound and should panic per rust's semantics.

**Comment by Michael-F-Bryan** [comment]
> Right now it also has a check if the array full, which in my opinion should be removed (you should still be able to insert something on index 2 in a [T; 8] array even if it's full).

I don't think this assumption is correct. If we allowed insertion into a full buffer, when shuffling items down the very last item would be moved *outisde* of the buffer. We *could* pop that last item from vector and `drop()` it, but I'd prefer not to silently throw away existing data when we run out of space.

> the check should be index >= self.len() because doing [1u8; 8][8] is obviously out of bound and should panic per rust's semantics.

Something to point out trying to insert at index `8` isn't the same as the `[1u8; 8][8]` indexing operation you wrote. I believe it's actually [intended behaviour](https://github.com/rust-lang/rust/blob/f1b882b55805c342e46ee4ca3beeef1d1fa2044b/src/liballoc/vec.rs#L990) (`index > self.len()` and `assert!(index <= len)` are equivalent) to be able to insert at the `self.len()`'th element.

That way you can write something like this:

```rust
let mut vector: ArrayVec<u8, { 10 }> = ArrayVec::new();
vector.push(0);
vector.push(1);
vector.push(2);
assert_eq!(vector.len(), 3);

vector.try_insert(3, 3).unwrap();
```

And it'll be logically equivalent to `vector.push(3)`.

---

I agree the code needs to make this clearer though. You're not the first person to point out that `try_insert()` is doing something which looks incorrect at first glance but is actually sound due to subtleties.

**Comment by elichai** [comment]
I somehow missed the fact that inserting shifts all the elements.

And it makes sense you want to make `vec.try_insert(vec.len(), T)` equivalent to `vec.push(T)`.

But I still think that if the index is equal to the capacity it should panic, because it's logically trying to access out of bounds, but I also understand if you don't want to add yet another if, so at least documenting that the `is_full` check is very important to soundness is a good thing :)
